use serde::{Deserialize, Serialize};

/// RFC 7807: Problem Details for HTTP APIs
/// Provides a standard way to represent errors in a machine-readable format.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ProblemDetails {
    /// A URI reference \[RFC3986\] that identifies the problem type.
    #[serde(rename = "type")]
    pub problem_type: String,

    /// A short, human-readable summary of the problem type.
    pub title: String,

    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    pub status: u16,

    /// A human-readable explanation specific to this occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,

    /// A URI reference that identifies the specific occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
}

impl ProblemDetails {
    pub fn new(problem_type: &str, title: &str, status: u16) -> Self {
        Self {
            problem_type: problem_type.to_string(),
            title: title.to_string(),
            status,
            detail: None,
            instance: None,
        }
    }

    pub fn with_detail(mut self, detail: &str) -> Self {
        self.detail = Some(detail.to_string());
        self
    }
}

impl From<crate::diagrams::error::DiagramError> for ProblemDetails {
    fn from(err: crate::diagrams::error::DiagramError) -> Self {
        use crate::diagrams::error::DiagramError::*;

        let (status, problem_type, title) = match &err {
            ValidationFailed(_) => (400, "validation-failed", "Input Validation Failed"),
            DecodeFailed(_) => (400, "decode-failed", "Input Decoding Failed"),
            UnsupportedFormat { .. } => (400, "unsupported-format", "Unsupported Format"),
            ToolNotFound(_) => (503, "tool-not-found", "Rendering Tool Missing"),
            ExecutionTimeout { .. } => (504, "execution-timeout", "Rendering Timed Out"),
            ProcessFailed(_) | Io(_) | Internal(_) => {
                (500, "internal-error", "Internal Server Error")
            }
        };

        Self::new(
            &format!("https://kroki.io/errors/{}", problem_type),
            title,
            status,
        )
        .with_detail(&err.to_string())
    }
}
